server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: https://digital-wallet-p.herokuapp.com/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - https://digital-wallet-p.herokuapp.com
    labels:
      job: project-team
      __path__: ../logs/example.log